[eanakim]
title = "kakaoTV ─ 톡이나 할까"
url = "https://tv.kakao.com/channel/3647846/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_contents"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[kyungkyulee]
title = "kakaoTV ─ 찐경규"
url = "https://tv.kakao.com/channel/3643851/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_contents"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[fightclub]
title = "kakaoTV ─ 파이트클럽"
url = "https://tv.kakao.com/channel/3887627/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_contents"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[antenna]
title = "kakaoTV ─ 더듬이TV 우당탕탕 안테나"
url = "https://tv.kakao.com/channel/3883129/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_contents"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[ttunttun5]
title = "kakaoTV ─ 더듬이TV 우당탕탕 안테나"
url = "https://tv.kakao.com/channel/3875615/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_contents"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[hiddentheperformance]
title = "kakaoTV ─ 히든 더 퍼포먼스"
url = "https://tv.kakao.com/channel/3879256/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_contents"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[runway2]
title = "kakaoTV ─ 런웨이2"
url = "https://tv.kakao.com/channel/3843430/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_contents"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"
